<a href="https://colab.research.google.com/github/Melquicedec-Aguilar/Tratamiento-de-datos-con-python/blob/main/02Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conceptos básicos de *Numpy*

[*Numpy*](http://www.numpy.org/) es un paquete que contiene una biblioteca de recursos especiales en realizar operaciones optimizadas en arreglos de datos

El proyecto *Numpy* cuenta con una extensa documentación, la cual esta disponible en https://docs.scipy.org/doc/numpy/

In [ ]:
#Instalacion del paquete
#!pip install numpy

In [1]:
#Importar el paquete numpy
import numpy as np

In [ ]:
arreglo = np.array([1,2,3])
arreglo

array([1. , 2. , 3. , 3.5])

In [ ]:
type(arreglo)

numpy.ndarray

In [ ]:
for i in arreglo:
  print("valor: {}, tipo: {}".format(i, type(i)))

valor: 1.0, tipo: <class 'numpy.float64'>
valor: 2.0, tipo: <class 'numpy.float64'>
valor: 3.0, tipo: <class 'numpy.float64'>
valor: 3.5, tipo: <class 'numpy.float64'>


In [ ]:
arreglo = np.array([1,2,3,3.5])
print(arreglo)
print(type(arreglo))
for i in arreglo:
  print("valor: {}, tipo: {}".format(i, type(i)))

[1.  2.  3.  3.5]
<class 'numpy.ndarray'>
valor: 1.0, tipo: <class 'numpy.float64'>
valor: 2.0, tipo: <class 'numpy.float64'>
valor: 3.0, tipo: <class 'numpy.float64'>
valor: 3.5, tipo: <class 'numpy.float64'>


In [ ]:
arreglo = np.array(['d',3, (12,6,True)], dtype=object)
for i in arreglo:
  print("valor: {}, tipo: {}".format(i, type(i)))


valor: d, tipo: <class 'str'>
valor: 3, tipo: <class 'int'>
valor: (12, 6, True), tipo: <class 'tuple'>


### El atributo ```shape```.

Los arreglos cuentan con el atributo ```shape```, el cual describe el número de elementos que contiene cada dimensión del arreglo.

El valor de ```shape``` es un objeto tipo tuple que contiene una sucesión de números.

```
(<n1>, <n2>, <n3> ... <nm>)
```

* Donde ```<n1>``` corresponde al número de elementos en la primera dimensión,  ```<n2> ```corresponde al número de elementos en la segunda dimensión y así sucesivamente hasta ```<nm>``` , la cual corrersponde al número de elementos de la dimensión ```m```

In [ ]:
arreglo = np.array((1,2,3))
print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo

1
(3,)
3


In [ ]:
#Arreglo bidimensional 
arreglo = np.array([[1,2,3],
                   [4,5,6]])

print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo

2
(2, 3)
6


In [ ]:
#Arreglo tridimensional 
arreglo = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])

print(arreglo.ndim) #Numero de dimensiones
print(arreglo.shape) #Numero de elementos en cada dimension
print(arreglo.size) #Numero total de elementos en el arreglo
print(arreglo)

3
(2, 2, 2)
8
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
np.array(((1,2), (3,4)))
#np.array(((1,2), (3,4))).shape

array([[1, 2],
       [3, 4]])

In [ ]:
#Tipo por default
np.array(((1,2), (3,4))).dtype

dtype('int64')

In [ ]:
np.array(((-1,2), (3,4)), dtype = np.uint8)

array([[255,   2],
       [  3,   4]], dtype=uint8)

In [ ]:
np.array(((-1,2), (3,4)), dtype = np.uint64)

array([[18446744073709551615,                    2],
       [                   3,                    4]], dtype=uint64)

In [ ]:
#Tipos complejos
complejo = np.array([[25.6j, 11.24],
                     [-21.890-15702174.43j, 0]])
print(complejo)
print(complejo.dtype)

[[  0.  +2.56000000e+01j  11.24+0.00000000e+00j]
 [-21.89-1.57021744e+07j   0.  +0.00000000e+00j]]
complex128


In [ ]:
np.array(((1, 'HOla'), (False,0)))

array([['1', 'HOla'],
       ['False', '0']], dtype='<U21')

In [ ]:
#Arreglo boleano
np.array(((1, 'HOla'), (False,0)), dtype = np.bool_) 

array([[ True,  True],
       [False, False]])

In [ ]:
#Tipo cadena
np.array((['Hugo', 'Paco'], ['Luis Ignacio', 'Donald']))

array([['Hugo', 'Paco'],
       ['Luis Ignacio', 'Donald']], dtype='<U12')

In [ ]:
np.array((['Hugo', 'Paco'], ['Luis Ignacio', 'Donald']), dtype = np.string_)

array([[b'Hugo', b'Paco'],
       [b'Luis Ignacio', b'Donald']], dtype='|S12')

In [ ]:
#Trabajar con fechas
from datetime import datetime

fechas = np.array([[np.datetime64("2019-08-25T23:59:45.231"), 
                   np.datetime64("2020-07-23")],
                   [np.datetime64(datetime(year=2018, month=12, day=22)),
                   np.datetime64("2019-03-01T11:25")]])

fechas

array([['2019-08-25T23:59:45.231000', '2020-07-23T00:00:00.000000'],
       ['2018-12-22T00:00:00.000000', '2019-03-01T11:25:00.000000']],
      dtype='datetime64[us]')

In [ ]:
#deltatime representa los segundos en un lapso de tiempo
print(datetime.now())
np.datetime64(datetime.now()) - fechas

2022-06-28 14:46:44.340093


array([[ 89650019110918,  60965204341918],
       [110990804341918, 104988104341918]], dtype='timedelta64[us]')

In [ ]:
a1 = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])

a2 = np.array([[[10,20], [30,40]],
                   [[50,60], [70,80]]])

a3 = np.array((100,200))

print(a1 + a2)
print('')
print(a1 * a2)
print('')
print(a1 * a3) #se puede generar la operacion si las dimensiones son diferentes pero sea el mismo shape

[[[11 22]
  [33 44]]

 [[55 66]
  [77 88]]]

[[[ 10  40]
  [ 90 160]]

 [[250 360]
  [490 640]]]

[[[ 100  400]
  [ 300  800]]

 [[ 500 1200]
  [ 700 1600]]]


In [ ]:
#ndarray    otra forma de generar arreglos el cual regresa un arreglo con valores no definidos cercanos a 0

np.ndarray((2,2), dtype=float)

array([[4.42929946e-310, 3.01208131e-310],
       [5.48367434e-310, 5.18710156e-310]])

In [ ]:
np.ndarray((2,2), dtype='>U10')

array([['', ''],
       ['', '']], dtype='>U10')

In [ ]:
np.ndarray((2,5,3,6))

array([[[[2.79130489e-316, 5.49370959e-317, 6.84774985e-321,
                      nan, 1.12646967e-321, 0.00000000e+000],
         [5.81241632e+180, 1.91560706e+227, 8.02678501e-095,
          1.14199444e+243, 1.05894728e-153, 6.65957504e-013],
         [6.54762579e+199, 7.29489530e+175, 1.04989162e-153,
          1.43273565e+228, 3.49824246e+228, 5.13042877e-095]],

        [[6.12030516e+257, 7.75891121e+228, 1.12759966e+257,
          1.69336693e-152, 5.81241632e+180, 6.19633416e+223],
         [1.23558994e-259, 4.90922779e+252, 4.47593784e-091,
          1.72861078e+270, 4.83245960e+276, 1.66041815e+243],
         [2.39090581e-258, 4.93418129e+257, 8.16552317e-085,
          2.93282800e+222, 1.06184931e-153, 1.66037173e+243]],

        [[1.94209101e+227, 2.59345489e+161, 1.42736776e+228,
          9.77824555e+199, 6.01334653e-154, 3.98388207e+252],
         [7.74412839e+228, 2.34950230e+251, 2.88854907e+214,
          7.75111104e+228, 1.32971161e-152, 4.23275990e+175],
         [1.

In [ ]:
#ones genera un arreglo exclusivamente con el numero 1 en cada elemento

np.ones((2,5,3,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],


In [ ]:
# zero genera un arreglo exclusivamente con el numero 0 en cada elemento
np.zeros((2,5,3,6))

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],


In [ ]:
np.zeros((2,2,2), dtype=bool)

array([[[False, False],
        [False, False]],

       [[False, False],
        [False, False]]])

In [ ]:
np.ones((2,2,2), dtype=bool)

array([[[ True,  True],
        [ True,  True]],

       [[ True,  True],
        [ True,  True]]])

In [ ]:
#empty genera arregls con valores aleatorios no inicializados 

np.empty((2,2,2), dtype=np.int8)

array([[[ 64,   7],
        [-40,   2]],

       [[  0,   0],
        [  0,   0]]], dtype=int8)

In [ ]:
# arange genera un arreglo unidimensional con valores enteros en un rango

np.arange(6,21)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
#(limite inferior, limite superior, salto)
np.arange(-30, 10, 4) 

array([-30, -26, -22, -18, -14, -10,  -6,  -2,   2,   6])

In [ ]:
# linspace genera un arreglo unidimensional con una secuencia lineal de valores dentro de un rango

np.linspace(0, 8)

array([0.        , 0.16326531, 0.32653061, 0.48979592, 0.65306122,
       0.81632653, 0.97959184, 1.14285714, 1.30612245, 1.46938776,
       1.63265306, 1.79591837, 1.95918367, 2.12244898, 2.28571429,
       2.44897959, 2.6122449 , 2.7755102 , 2.93877551, 3.10204082,
       3.26530612, 3.42857143, 3.59183673, 3.75510204, 3.91836735,
       4.08163265, 4.24489796, 4.40816327, 4.57142857, 4.73469388,
       4.89795918, 5.06122449, 5.2244898 , 5.3877551 , 5.55102041,
       5.71428571, 5.87755102, 6.04081633, 6.20408163, 6.36734694,
       6.53061224, 6.69387755, 6.85714286, 7.02040816, 7.18367347,
       7.34693878, 7.51020408, 7.67346939, 7.83673469, 8.        ])

In [ ]:
np.linspace(0, 8, num=100)

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [ ]:
#Ecribir en un archivo txt
arreglo = np.linspace(0, 8, num=100)

np.savetxt('arreglo.txt', arreglo)

In [ ]:
#Ecribir en un archivo binario
np.save('arreglo', arreglo)

In [ ]:
#Leer archivo
arreglo2 = np.loadtxt('arreglo.txt')
arreglo2

array([0.        , 0.08080808, 0.16161616, 0.24242424, 0.32323232,
       0.4040404 , 0.48484848, 0.56565657, 0.64646465, 0.72727273,
       0.80808081, 0.88888889, 0.96969697, 1.05050505, 1.13131313,
       1.21212121, 1.29292929, 1.37373737, 1.45454545, 1.53535354,
       1.61616162, 1.6969697 , 1.77777778, 1.85858586, 1.93939394,
       2.02020202, 2.1010101 , 2.18181818, 2.26262626, 2.34343434,
       2.42424242, 2.50505051, 2.58585859, 2.66666667, 2.74747475,
       2.82828283, 2.90909091, 2.98989899, 3.07070707, 3.15151515,
       3.23232323, 3.31313131, 3.39393939, 3.47474747, 3.55555556,
       3.63636364, 3.71717172, 3.7979798 , 3.87878788, 3.95959596,
       4.04040404, 4.12121212, 4.2020202 , 4.28282828, 4.36363636,
       4.44444444, 4.52525253, 4.60606061, 4.68686869, 4.76767677,
       4.84848485, 4.92929293, 5.01010101, 5.09090909, 5.17171717,
       5.25252525, 5.33333333, 5.41414141, 5.49494949, 5.57575758,
       5.65656566, 5.73737374, 5.81818182, 5.8989899 , 5.97979

In [ ]:
#Listar el contenido de un directorio

%ls

arreglo.npy  arreglo.txt  sample_data/


In [ ]:
#Ver el contenido de un archivo

%cat arreglo.txt

0.000000000000000000e+00
8.080808080808081495e-02
1.616161616161616299e-01
2.424242424242424310e-01
3.232323232323232598e-01
4.040404040404040886e-01
4.848484848484848619e-01
5.656565656565657463e-01
6.464646464646465196e-01
7.272727272727272929e-01
8.080808080808081773e-01
8.888888888888889506e-01
9.696969696969697239e-01
1.050505050505050608e+00
1.131313131313131493e+00
1.212121212121212155e+00
1.292929292929293039e+00
1.373737373737373924e+00
1.454545454545454586e+00
1.535353535353535470e+00
1.616161616161616355e+00
1.696969696969697017e+00
1.777777777777777901e+00
1.858585858585858785e+00
1.939393939393939448e+00
2.020202020202020332e+00
2.101010101010101216e+00
2.181818181818182101e+00
2.262626262626262985e+00
2.343434343434343425e+00
2.424242424242424310e+00
2.505050505050505194e+00
2.585858585858586078e+00
2.666666666666666963e+00
2.747474747474747847e+00
2.828282828282828731e+00
2.909090909090909172e+00
2.989898989898990056e+00
3.070707070707070940e+00
3.151515151515151825e+00


In [ ]:
#Guardar mas d eun arreglo en un solo archivo

np.savez('arreglos', a1, a2, a3)

In [ ]:
%cat arreglos.npz

PK!y�~6��	arr_0.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2, 2), }                                                       
PK!������	arr_1.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2, 2, 2), }                                                       

(2<FPPK!b�bA��	arr_2.npy���NUMPYv{'descr': '<i8', 'fortran_order': False, 'shape': (2,), }                                                            
d�PK!y�~6��	�arr_0.npyPK!������	��arr_1.npyPK!b�bA��	��arr_2.npyPK��

In [ ]:
#Leer varios arreglos desde un archivo

cargados = np.load('arreglos.npz')
cargados

In [ ]:
#Acceder a un arreglo cargado

cargados['arr_0']

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
with cargados as arr:
  for i in arr:
    print(i, arr[i])

arr_0 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr_1 [[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]
arr_2 [100 200]


In [ ]:
with np.load('arreglos.npz') as arr:
  ac3 = arr['arr_2']
ac3

array([100, 200])

#Operaciones basicas con arreglos.


La siguiente tabla ejemplifica la conformación de las Equipos en una semana dada.

||Equipo 1| Equipo 2|
|:--:|:---:|:---:|
|*Lunes*|Lilia, Antonio, Ricardo|Alonso, Jorge, Salvador|
|*Martes*|Mariana, Julian, Ricardo|Arturo, Ramy, Esteban|
|*Miércoles*|Arturo, Ricardo, Lucio|Jorge, Marco, Lilia|
|*Jueves*|Alonso, Julian, Salvador|Ricardo, Jorge, Esteban|
|*Viernes*|Lucio, Ramy, Joaquín|Ricardo, Marco, Lilia|

In [2]:
equipos = np.array([[['Lilia', 'Antonio', 'Ricardo'], ['Alonso', 'Jorge', 'Salvador']],
                    [['Mariana', 'Julian', 'Ricardo'], ['Arturo', 'Ramy', 'Esteban']],
                    [['Arturo', 'Ricardo', 'Lucio'], ['Jorge', 'Marco', 'Lilia']],
                    [['Alonso', 'Julian', 'Salvador'], ['Ricardo', 'Jorge', 'Esteban']],
                    [['Lucio', 'Ramy', 'Joaquín'], ['Ricardo', 'Marco', 'Lilia']]])

In [ ]:
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramy', 'Joaquín'],
        ['Ricardo', 'Marco', 'Lilia']]], dtype='<U8')

In [ ]:
print(equipos.ndim)
print(equipos.shape)
print(equipos.size)

3
(5, 2, 3)
30


In [ ]:
#Slices de arreglos
#Se visualiza los dias martes y miercoles de la semana
equipos[1:3]

array([[['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']]], dtype='<U8')

In [ ]:
equipos[1:3].shape

(2, 2, 3)

In [ ]:
#Ver el equipo 2 de los dias martes y miercoles de la semana 
equipos[1:3, 1]

array([['Arturo', 'Ramy', 'Esteban'],
       ['Jorge', 'Marco', 'Lilia']], dtype='<U8')

In [ ]:
equipos[1:3, 1].shape

(2, 3)

In [ ]:
#Ver los 2 primeros intengrantes del equipo 2 de los dias martes y miercoles de la semana 
equipos[1:3, 1, 0:2]

array([['Arturo', 'Ramy'],
       ['Jorge', 'Marco']], dtype='<U8')

In [ ]:
equipos[1:3, 1, 0:2].shape

(2, 2)

In [ ]:
#Ver el tercer intengrante del equipo 1 de todos los dias
print(equipos[:, 0, 2:3])

#tambien puede ser de la siguiente manera
print(equipos[:, 0, 2])

[['Ricardo']
 ['Ricardo']
 ['Lucio']
 ['Salvador']
 ['Joaquín']]
['Ricardo' 'Ricardo' 'Lucio' 'Salvador' 'Joaquín']


In [ ]:
#Localizar al integrante 3 del equipo 2 del día viernes
equipos[4, 1, 2:3]

array(['Lilia'], dtype='<U8')

In [ ]:
print(type(equipos[4, 1, 2:3]))
print(equipos[4, 1, 2:3].shape)
print(equipos[4, 1, 2:3].size)

<class 'numpy.ndarray'>
(1,)
1


#Remplazos

|Equipo 1| Equipo 2|
:---:|:---:|
|Paulina, Rigo, Paul|Kenia, Miguel, Carlos|

In [4]:
remplazos = np.array([['Paulina', 'Rigo', 'Paul'], 
               ['Kenia', 'Miguel', 'Carlos']])

remplazos

array([['Paulina', 'Rigo', 'Paul'],
       ['Kenia', 'Miguel', 'Carlos']], dtype='<U7')

In [ ]:
remplazos.shape

(2, 3)

In [ ]:
equipos[:]

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Lucio', 'Ramy', 'Joaquín'],
        ['Ricardo', 'Marco', 'Lilia']]], dtype='<U8')

In [ ]:
equipos[4]

array([['Lucio', 'Ramy', 'Joaquín'],
       ['Ricardo', 'Marco', 'Lilia']], dtype='<U8')

In [ ]:
equipos[4].shape

(2, 3)

In [5]:
#Cambiar elementos de un arreglo
equipos[4] = remplazos
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Arturo', 'Ricardo', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [9]:
#Cambiar dos elementos de un arreglo
equipos[2, 0, 0:2] = ['Julio', 'Ernesto']
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esteban']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [16]:
#Cambiar un solo elemento
equipos[3, 1, 2] = 'Esmeralda'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Paulina', 'Rigo', 'Paul'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [23]:
#ES posible identificaar elementos de una dimension usando arreglos como indices
idx_1 = np.array([2,0,3])
print(idx_1)
print(equipos[idx_1])
print(equipos[idx_1].shape)

[2 0 3]
[[['Julio' 'Ernesto' 'Lucio']
  ['Jorge' 'Marco' 'Lilia']]

 [['Lilia' 'Antonio' 'Ricardo']
  ['Alonso' 'Jorge' 'Salvador']]

 [['Alonso' 'Julian' 'Salvador']
  ['Ricardo' 'Jorge' 'Esmerald']]]
(3, 2, 3)


In [22]:
idx_2 = np.array([[0,3], [1,4]])
print(idx_2)
print(equipos[idx_2])
print(equipos[idx_2].shape)

[[0 3]
 [1 4]]
[[[['Lilia' 'Antonio' 'Ricardo']
   ['Alonso' 'Jorge' 'Salvador']]

  [['Alonso' 'Julian' 'Salvador']
   ['Ricardo' 'Jorge' 'Esmerald']]]


 [[['Mariana' 'Julian' 'Ricardo']
   ['Arturo' 'Ramy' 'Esteban']]

  [['Paulina' 'Rigo' 'Paul']
   ['Kenia' 'Miguel' 'Carlos']]]]
(2, 2, 2, 3)


In [26]:
#uso de multiples arreglos como indices
print(equipos)
print("")
idx_x = np.array([0,2])  #Lunes y Miercoles
idx_y = np.array([0,1]) #equipo 1 y 2
print("---------------------------------------")
print(equipos[idx_x, idx_y])

[[['Lilia' 'Antonio' 'Ricardo']
  ['Alonso' 'Jorge' 'Salvador']]

 [['Mariana' 'Julian' 'Ricardo']
  ['Arturo' 'Ramy' 'Esteban']]

 [['Julio' 'Ernesto' 'Lucio']
  ['Jorge' 'Marco' 'Lilia']]

 [['Alonso' 'Julian' 'Salvador']
  ['Ricardo' 'Jorge' 'Esmerald']]

 [['Paulina' 'Rigo' 'Paul']
  ['Kenia' 'Miguel' 'Carlos']]]

---------------------------------------
[['Lilia' 'Antonio' 'Ricardo']
 ['Jorge' 'Marco' 'Lilia']]


In [27]:
equipos[4,0] = 'Fabian'
equipos

array([[['Lilia', 'Antonio', 'Ricardo'],
        ['Alonso', 'Jorge', 'Salvador']],

       [['Mariana', 'Julian', 'Ricardo'],
        ['Arturo', 'Ramy', 'Esteban']],

       [['Julio', 'Ernesto', 'Lucio'],
        ['Jorge', 'Marco', 'Lilia']],

       [['Alonso', 'Julian', 'Salvador'],
        ['Ricardo', 'Jorge', 'Esmerald']],

       [['Fabian', 'Fabian', 'Fabian'],
        ['Kenia', 'Miguel', 'Carlos']]], dtype='<U8')

In [30]:
#Un mismo arreglo para todos los elementos de la dimension 
equipos[2] = np.array(['Hugo', 'Paco', 'Luis'])
print(equipos[2].shape)
print(equipos)

(2, 3)
[[['Lilia' 'Antonio' 'Ricardo']
  ['Alonso' 'Jorge' 'Salvador']]

 [['Mariana' 'Julian' 'Ricardo']
  ['Arturo' 'Ramy' 'Esteban']]

 [['Hugo' 'Paco' 'Luis']
  ['Hugo' 'Paco' 'Luis']]

 [['Alonso' 'Julian' 'Salvador']
  ['Ricardo' 'Jorge' 'Esmerald']]

 [['Fabian' 'Fabian' 'Fabian']
  ['Kenia' 'Miguel' 'Carlos']]]
