<a href="https://colab.research.google.com/github/Melquicedec-Aguilar/Tratamiento-de-datos-con-python/blob/main/03NumpyOperaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importar el paquete numpy
import numpy as np

In [4]:
m1= np.array([[1,2,3], 
             [10,11,12],
             [-5,-8,-14]])
print(m1)
print(m1.shape)

[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [3]:
#Las operaciones aritmeticas se aplican a todos los elementos de cada matriz

m1 * 200

array([[  200,   400,   600],
       [ 2000,  2200,  2400],
       [-1000, -1600, -2800]])

In [5]:
#Aplicar la operacion a un elemento 

m1[1] + 15

array([25, 26, 27])

In [7]:
m1 / 5.45

array([[ 0.18348624,  0.36697248,  0.55045872],
       [ 1.83486239,  2.01834862,  2.20183486],
       [-0.91743119, -1.46788991, -2.56880734]])

In [8]:
#Usar operadores logicos por broadcasting
m1 > 1

array([[False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [10]:
m2 = np.array([1,2,3])
m3= np.array([[2], [4], [6]])

print(m2)
print(m2.shape)
print(m3)
print(m3.shape)
print(m1)
print(m1.shape)

[1 2 3]
(3,)
[[2]
 [4]
 [6]]
(3, 1)
[[  1   2   3]
 [ 10  11  12]
 [ -5  -8 -14]]
(3, 3)


In [11]:
m1 * m2

array([[  1,   4,   9],
       [ 10,  22,  36],
       [ -5, -16, -42]])

In [12]:
m1 /m3

array([[ 0.5       ,  1.        ,  1.5       ],
       [ 2.5       ,  2.75      ,  3.        ],
       [-0.83333333, -1.33333333, -2.33333333]])

In [13]:
m4 = m1 + 20
m4

array([[21, 22, 23],
       [30, 31, 32],
       [15, 12,  6]])

In [14]:
m1 * m4

array([[ 21,  44,  69],
       [300, 341, 384],
       [-75, -96, -84]])

In [18]:
#Generar arreglos con valores aleatorios
np.random.rand(2,2,2)

array([[[0.65383263, 0.80200672],
        [0.6414001 , 0.47079533]],

       [[0.07693916, 0.31553211],
        [0.856149  , 0.29274797]]])

In [27]:
#radint genera valores enteros aleatorios entre un rango
np.random.randint(1,4,(2,2,2)) 

array([[[1, 1],
        [1, 1]],

       [[2, 1],
        [1, 2]]])

In [20]:
np.random.randint(0,255,(3,2,4)) 

array([[[243, 215,  28, 164],
        [  8, 237, 174, 133]],

       [[ 40, 141, 193,  38],
        [210, 158,  43, 225]],

       [[169, 240, 141, 200],
        [ 38,  56, 124, 251]]])

In [29]:
numeros = np.array([[2.43, -3, 48.9999, -5.61],
                   [np.inf, -np.inf, np.inf, np.inf],
                   [np.nan, 17.78, 12, 22]])

numeros

array([[ 2.43  , -3.    , 48.9999, -5.61  ],
       [    inf,    -inf,     inf,     inf],
       [    nan, 17.78  , 12.    , 22.    ]])

## Funciones de valor
* ```np.abs()```
* ```np.around()```
* ```np.ceil()```
* ```np.exp()```
* ```np.exp2()```
* ```np.fabs()```
* ```np.fix()```
* ```np.floor()```
* ```np.log()```
* ```np.log10()```
* ```np.log1p()```
* ```np.log2()```
* ```np.logaddexp()```
* ```np.logaddexp2()```
* ```np.round()```

In [30]:
#Funciones de valor
print(np.abs(numeros))
print(np.floor(numeros))
print(np.ceil(numeros))
print(np.round(numeros))

[[ 2.43    3.     48.9999  5.61  ]
 [    inf     inf     inf     inf]
 [    nan 17.78   12.     22.    ]]
[[  2.  -3.  48.  -6.]
 [ inf -inf  inf  inf]
 [ nan  17.  12.  22.]]
[[  3.  -3.  49.  -5.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]
[[  2.  -3.  49.  -6.]
 [ inf -inf  inf  inf]
 [ nan  18.  12.  22.]]


In [32]:
#Funciones de evaluacion de arreglos
print(np.isfinite(numeros))
print(np.isnan(numeros))
print(np.isreal(numeros))
print(np.isscalar(numeros))

[[ True  True  True  True]
 [False False False False]
 [False  True  True  True]]
[[False False False False]
 [False False False False]
 [ True False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
False


## Funciones estadísticas.

* ```np.amax()```
* ```np amin()```
* ```np.argmax()```
* ```np.argmin()```
* ```np.average()```
* ```np.correlate()```
* ```np.corrcoef()```
* ```np.count_nonzero()```
* ```np.cov()```
* ```np.cumprod()```
* ```np.cumsum()```
* ```np.histogram()```
* ```np.histogram2d()```
* ```np.histogram_bin_edges()```
* ```np.histogramdd()```
* ```np.max()```
* ```np.mean()```
* ```np.median()```
* ```np.min()```
* ```np.nanargmax()```
* ```np.nanargmin()```
* ```np.nancumprod()```
* ```np.nancumsum()```
* ```np.nanmax()```
* ```np.nanmean()```
* ```np.nanmedian()```
* ```np.nanmin()```
* ```np.nanpercentile()```
* ```np.nanquantile()```
* ```np.nanstd()```
* ```np.nansum()```
* ```np.nanvar()```
* ```np.percentile()```
* ```np.quantile()```
* ```np.std()```
* ```np.var()```

In [33]:
numeros = np.random.randint(0, 256, (3,2,4))
numeros

array([[[191, 114, 111,  94],
        [  8, 119, 146,  70]],

       [[ 30, 176, 156, 139],
        [ 60, 115, 196,  71]],

       [[ 56,  83, 112,  90],
        [119, 215, 112,   8]]])

In [34]:
print(np.max(numeros))
print(np.mean(numeros))
print(np.min(numeros))
print(np.median(numeros))

215
107.95833333333333
8
112.0


In [35]:
print(np.nanmax(numeros))
print(np.nanmin(numeros))
print(np.nanmean(numeros))
print(np.nanmedian(numeros))

215
8
107.95833333333333
112.0


In [36]:
np.histogram(numeros)

(array([2, 1, 3, 3, 2, 6, 2, 1, 2, 2]),
 array([  8. ,  28.7,  49.4,  70.1,  90.8, 111.5, 132.2, 152.9, 173.6,
        194.3, 215. ]))

In [37]:
#Copia y ordenamiento
numeros1 = numeros #alias en un arreglo
numeros1 = np.copy(numeros) #copia del arreglo
numeros1

array([[[191, 114, 111,  94],
        [  8, 119, 146,  70]],

       [[ 30, 176, 156, 139],
        [ 60, 115, 196,  71]],

       [[ 56,  83, 112,  90],
        [119, 215, 112,   8]]])

In [39]:
numeros1.sort()
numeros1

array([[[ 94, 111, 114, 191],
        [  8,  70, 119, 146]],

       [[ 30, 139, 156, 176],
        [ 60,  71, 115, 196]],

       [[ 56,  83,  90, 112],
        [  8, 112, 119, 215]]])

In [40]:
numeros1.sort(axis=2)
numeros1

array([[[ 94, 111, 114, 191],
        [  8,  70, 119, 146]],

       [[ 30, 139, 156, 176],
        [ 60,  71, 115, 196]],

       [[ 56,  83,  90, 112],
        [  8, 112, 119, 215]]])

In [45]:
numeros1.sort(axis=0)
numeros1

array([[[  8,  70,  90, 112],
        [ 56, 111, 119, 191]],

       [[  8,  71, 114, 146],
        [ 60, 112, 119, 196]],

       [[ 30,  83, 115, 176],
        [ 94, 139, 156, 215]]])

In [46]:
a = np.array([1, 2, 3])
b = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print(b)
print(np.add(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]


In [47]:
#Suma total de los elementos
b.sum()

21

In [48]:
#Raiz cuadrada
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [49]:
#Crear un arreglo con los resiltados de una comparacion logica
c = b <= 4
c

array([[ True,  True,  True],
       [ True, False, False]])